### ISSUE TITLE
RP4 Installation Error on Bullseye

### ISSUE THREAD

**Issue by daBee** [morrownr/8821cu#41]
Error in a RP4 installation on Bullseye:

```
[Sun Jan 16 00:20:49 pi@sniff ~/build/8821cu] sudo ./install-driver.sh
Running install-driver.sh version 20210725
Starting installation.
Copying source files to: /usr/src/rtl8821cu-5.8.1.7
Copying 8821cu.conf to: /etc/modprobe.d

Creating symlink /var/lib/dkms/rtl8821cu/5.8.1.7/source ->
                 /usr/src/rtl8821cu-5.8.1.7

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.10.63-v7l+ KSRC=/lib/modules/5.10.63-v7l+/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.63-v7l+ (armv7l)
Consult /var/lib/dkms/rtl8821cu/5.8.1.7/build/make.log for more information.
An error occurred. dkms build error = 10
Please report this error.
```
...which is...

```
DKMS make.log for rtl8821cu-5.8.1.7 for kernel 5.10.63-v7l+ (armv7l)
Sun 16 Jan 2022 12:21:00 AM EST
make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/5.10.63-v7l+/build M=/var/lib/dkms/rtl8821cu/5.8.1.7/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.63-v7l+'
  CC [M]  /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_io.o
In file included from ./include/linux/types.h:6,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/basic_types.h:75,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_cmd.c:17:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
In file included from ./include/linux/types.h:6,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/basic_types.h:75,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_debug.c:17:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
In file included from ./include/linux/types.h:6,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/basic_types.h:75,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_io.c:47:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
In file included from ./include/linux/types.h:6,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/basic_types.h:75,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_security.c:17:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_io.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_cmd.o] Error 1
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_debug.o] Error 1
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/rtl8821cu/5.8.1.7/build/core/rtw_security.o] Error 1
make[1]: *** [Makefile:1825: /var/lib/dkms/rtl8821cu/5.8.1.7/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.63-v7l+'
make: *** [Makefile:2374: modules] Error 2
```

**Comment by morrownr** [comment]
Right before you run ./install-driver.sh, since you run the RasPiOS, there is a need to run either raspi32.sh or raspi64.sh.

It appears that you are running the standard 32 bit version of RasPiOS. My best guess as to the problem right now is either you skipped that step or you ran the wrong one. 

You will need to run ./remove-driver.sh before you try again.

Regards

**Comment by daBee** [comment]
And of course my unit won't start now.  I did choose the wrong version, btw.

**Comment by morrownr** [comment]
It happens. Sometimes you just need to go pour yourself a cup of coffee and relax for a few minutes.

I've tried to do the best I can to make things easy and reliable but there is only so much you can do given the way Realtek mkes their drivers.

**Comment by daBee** [comment]
Well, drove 20 minutes to pick up 2 top end SD cards.  Drove back, flashed `ROS` onto one, tried to start up, and startup continues to fail half way through.  ...ya.  

Anyway, `Realtek` should understand people are looking for updated drivers.  Oh, I was going to mention, your **raspiXX.sh** script can sniff the memory width using `getconf LONG_BIT`, so you can shove those into a single script.

**Comment by morrownr** [comment]
> Well, drove 20 minutes to pick up 2 top end SD cards. Drove back, flashed `ROS` onto one, tried to start up, and startup continues to fail half way through. ...ya.

When you say "startup" fails, are you talking about the Pi or the driver installation?
 
> Anyway, `Realtek` should understand people are looking for updated drivers.

Yeah, I'm not a fan of Realtek. I just do this to help fellow Linux users. I also maintain this repo so that Linux users are aware that there are alternatives:

https://github.com/morrownr/USB-WiFi

> Oh, I was going to mention, your **raspiXX.sh** script can sniff the memory width using `getconf LONG_BIT`, so you can shove those into a single script.

I had briefly thought about investigating a way to do that a long time ago but it seems I am always busy. Heck, maybe I can combine it all in the installation script.

**Comment by daBee** [comment]
The `Pi`.  The test scrolls, then monitor goes blank, says "no connection".  

Ya shove that small instruction into a conditional and both can run in the same script.

**Comment by daBee** [comment]
BTW I use mine in `monitor mode`.  I bought it because it could do this on both 2.4 and 5.8 GHz.  Worked fine before my `Pi` got sick.

**Comment by lehni** [comment]
This fixed the problem for me, before running `install-driver.sh`:

```
sed -i 's/^MAKE="/MAKE="ARCH=arm\ /' 8821cu/dkms.conf
```
